---

- name: Ensure Erglang cookie is set for users
  become: yes
  template:
    src: doterlang.cookie.j2
    dest: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0600
  loop:
    - path: /root/.erlang.cookie
      owner: root
      group: root
    - path: /var/lib/rabbitmq/.erlang.cookie
      owner: rabbitmq
      group: rabbitmq

- name: Ensure the HA policy exists to enable mirroring for the cluster
  become: yes
  rabbitmq_policy:
    name: ha-all
    pattern: .*
    tags:
      ha-mode: all
      ha-sync-mode: automatic
  notify:
    - restart rabbitmq

- name: Gather cluster information
  become: yes
  command: rabbitmqctl cluster_status
  register: cluster_status
  changed_when: false

- name: Reset non-master nodes so they can join the cluster if they are not part of it already
  become: yes
  command: "{{ item }}"
  when: inventory_hostname != rabbitmq_master_node and cluster_status.stdout.find('rabbit@' ~ rabbitmq_master_hostname) == -1
  with_items:
    - rabbitmqctl stop_app
    - rabbitmqctl reset
    - rabbitmqctl start_app