---

- name: Ensure the guest user is removed
  become: yes
  rabbitmq_user:
    user: guest
    state: absent

- name: Ensure users are present
  become: yes
  rabbitmq_user:
      user: "{{ item.user }}"
      password: "{{ item.password }}"
      configure_priv: "{{ item.configure_priv | default('.*') }}"
      read_priv: "{{ item.read_priv | default('.*') }}"
      write_priv: "{{ item.write_priv | default('.*') }}"
      vhost: "{{ item.vhost | default('/') }}"
      tags: "{{ item.tags| default('') }}"
  with_items: "{{rabbitmq_users}}"


- name: Ensure plugins are present
  become: yes
  rabbitmq_plugin:
    names: "{{ item }}"
    state: enabled
    new_only: yes
  with_items: "{{ rabbitmq_plugins }}"
  notify:
    - restart rabbitmq


- name: Add configuration file
  become: yes
  template:
    src: rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
    owner: rabbitmq
    group: rabbitmq
    mode: 0644
  notify:
    - restart rabbitmq



- name: Ensure Erglang cookie is the same for root user
  become: yes
  template:
    src: .erlang.cookie.j2
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - /root/.erlang.cookie

- name: ensure the default vhost contains the HA policy via a dict
  become: yes
  rabbitmq_policy:
    name: ha-all
    pattern: ""
    tags:
      ha-mode: all
      ha-sync-mode: automatic
  notify:
    - restart rabbitmq