---


- name: Fail if Rabbitmq is disabled
  fail:
    msg: "RabbitMQ is disabled"
  when: not rabbitmq_enabled
  tags:
    - rabbitmq

#- include: install.yml
#  tags:
#    - rabbitmq

- include: configure.yml
  tags:
    - rabbitmq
